
version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "cloudbash-frontend"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - cd src/WebUI
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
artifacts:
    files:
        - '**/*'
    base-directory: 'src/WebUI/dist*'
    discard-paths: yes