name: dotnet

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Build  project
      working-directory: ./
      run: dotnet build 

    - name: Test Application project
      working-directory: ./tests/Application.UnitTests
      run: |            
          dotnet test /p:Exclude="[xunit*]*" /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
              
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./tests/Application.UnitTests/TestResults/coverage.info   
        flag-name: run-1          
        parallel: true


    - name: Test Application project
      working-directory: ./tests/Domain.UnitTests
      run: |            
          dotnet test /p:Exclude="[xunit*]*" /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
              
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./tests/Domain.UnitTests/TestResults/coverage.info 
        flag-name: run-2
        parallel: true



  finish:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true